# Generated by Django 4.2.6 on 2025-01-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='location_images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Изображение локации',
                'verbose_name_plural': 'Изображения локаций',
                'ordering': ['order'],
            },
        ),
    ]
