# Generated by Django 4.2.6 on 2025-01-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_location_options_alter_locationimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description_long',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='location',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
