# Generated by Django 4.2.6 on 2025-01-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_location_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='details_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL для деталей'),
        ),
    ]
