# Generated by Django 4.2.6 on 2025-01-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_location_details_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='details_url',
        ),
        migrations.RemoveField(
            model_name='location',
            name='place_id',
        ),
    ]
