# Generated by Django 4.2.6 on 2025-01-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
