# Generated by Django 4.2.6 on 2025-01-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_location_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
